name: Automated Testing and Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
    
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Run the deployment script
        uses: appleboy/ssh-action@v1.0.0
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            port: ${{ secrets.PORT }}
            script: |
                ./shareact_be_deploy.sh